### ISSUE TITLE
Webhook is called even if it is not configured

### ISSUE THREAD

**Issue by redakker** [redakker/blecker#14]
In webhook.cpp the webhookConfigured value is always true.
It is calculated wrong in the setup() function

**Comment by redakker** [comment]
Fixed

**Comment by ozett** [comment]
was still there - in my downloaded bin... 
whats this version?
![image](https://user-images.githubusercontent.com/5937811/156373417-80964e41-6185-44ef-b6de-b31d8e8deefd.png)

**Comment by redakker** [comment]
@ozett 
Please use the latest code
