### ISSUE TITLE
[Support]: Flashing to ES32-CAM (ESP32-S Board)

### ISSUE THREAD

**Issue by ozett** [redakker/blecker#15]
Flashing failed. can anybod confirm that the binary works/flashes to  ES32-CAM (ESP32-S Board) ?
will try some other board...

**Comment by redakker** [comment]
Hi,

Yes, I have never tried ESP32-CAM. But it looks you have done it well.

**Comment by ozett** [comment]
ver 1.05 reboots in an error loop with 0x13...
i flashed the binary different boards and different ways, but seems to be the binary..
(hope to see 1.06 and give it another try before i make a virtualpc to compile all myself)

![image](https://user-images.githubusercontent.com/5937811/156512328-447e536e-327c-47da-b27c-0a178bf8b2dd.png)

**Comment by redakker** [comment]
@ozett
I've never used this tool so I can't help sorry.
esptool works fine for me.
Try VSCode as well.

1.06 binary file was missing from the release. I had to upload it again.
From now it is available

**Comment by ozett** [comment]
> esptool works fine for me.

what adress do you use 0x1000 in esptool ?

will give it another try with 1.06 binary.

**Comment by redakker** [comment]
@ozett 
I use esptool with VSCode. The upload and all parameters are done with this tool.
I need to do some experiments to answer your question

**Comment by ozett** [comment]
ver 1.06 looks better.
tried again with esphome-flasher like all the times before, but this looks better

![image](https://user-images.githubusercontent.com/5937811/156524727-b93e23cb-5676-4b3e-b66d-fdb8cad2a04e.png)

**Comment by ozett** [comment]
Version-Nr in Web-GUI not upt to date

not 1.06, instead "version v-orig"

**Comment by ozett** [comment]
this binary v1.06 seems to works good

![image](https://user-images.githubusercontent.com/5937811/156525379-d4440801-f58d-4728-a369-30ce4da4d25f.png)

**Comment by ozett** [comment]
i flashed v1.07 on espcam32.
confirm that this board works! (for readme.md)?

**Comment by redakker** [comment]
Cool, thank you. I'll update the documentation

**Comment by ozett** [comment]
if you collect some board-stats somewhere,
i can upload info from some other boards next update..

![image](https://user-images.githubusercontent.com/5937811/158077738-d18b31f2-7b49-4530-a66b-a99168cdb576.png)

**Comment by redakker** [comment]
I think it is possible from outside, before the upload.
I'll try to find the right tool for that.

**Comment by ozett** [comment]
i have some devices running with "espeasy",
they do it somehow like this (maybe this helps):

outside:
https://github.com/letscontrolit/ESPEasy/blob/7e7c6020721da9ceabb9d6d03bddb84e0751f2bd/test/esptool.py#L268

inside:
https://github.com/letscontrolit/ESPEasy/blob/65e5bbcefa213bdca52e246bb8f6cdf793315549/src/_Reporting.ino#L36
