### ISSUE TITLE
[FR:] JSON out  & MQTT /status

### ISSUE THREAD

**Issue by ozett** [redakker/blecker#19]
the detailed status is send as JSON over MQTT,
but the message "present/away" is not. 

i request all JSON, because its more likely . and better for node-red.

also

would like another topic to simply filter on in node red
would let me easily filter for all rssi 

💚 /blecker/status/1234id...

🟥  (instead of /blecker/1234id.../status)

![image](https://user-images.githubusercontent.com/5937811/156442240-547ae02b-1219-435e-8582-fc028ee61c8d.png)

**Comment by redakker** [comment]
But the JSON contains the presence status.
The topic change makes sense, I'll fix it in a couple of minutes. Come back to you

**Comment by redakker** [comment]
It takes more than expected, I write a comment here if it is done

**Comment by redakker** [comment]
@ozett 
Done
The new version 1.06 is released. Please read the details in the readme and the release documentation.
Thank you for your detailed reports. It helped a lot.
And thank you for your contribution, test, and usage!

**Comment by ozett** [comment]
hoped to find a ver 1.06 binary ... 😢

**Comment by ozett** [comment]
why is /blecker added to the base-topic?

i would assume topics as:

/base-topic/status
/base-topic/ids...


![image](https://user-images.githubusercontent.com/5937811/156526921-ce50744c-cb97-4a19-aeb6-101f2b1a25e3.png)

**Comment by ozett** [comment]
also the change to JSON-payload did not work.
this is no JSON from v1.06..

![image](https://user-images.githubusercontent.com/5937811/156527309-51d2fb9c-59bc-473f-bc9d-4c650e74f9f0.png)

**Comment by redakker** [comment]
> why is /blecker added to the base-topic?
> 
> i would assume topics as:
> 
> `/base-topic/status`
> 
> and `/base-topic/ids...` or `` /blacker/devices/`ids... ``
> 
> ![image](https://user-images.githubusercontent.com/5937811/156526921-ce50744c-cb97-4a19-aeb6-101f2b1a25e3.png)

This is how it works. /blecker is there always

**Comment by redakker** [comment]
> also the change to JSON-payload did not work. this is no JSON from v1.06..
> 
> ![image](https://user-images.githubusercontent.com/5937811/156527309-51d2fb9c-59bc-473f-bc9d-4c650e74f9f0.png)

Switch on the detailed report and you will get a JSON format in another topic
/blecker/status/[device-mac]: {"rssi":"..." ....}

**Comment by redakker** [comment]
@ozett 
The basic presence status will not be changed. Just you can add more with the detailed riport.

**Comment by ozett** [comment]
if messages come in details as JSON
and also as "normal" messages not as JSON,
my debug is flooded with errors.

i can filter this out in node-red.
but maybe better to have one - or the other?

maybe:
if detail is ON, than "nomal" also is JSON.

-> DETAIL ON == JSON ON ?

![image](https://user-images.githubusercontent.com/5937811/156531325-e594d29a-2c50-4a60-bd3c-a8e14614c4af.png)

**Comment by redakker** [comment]
Subscribe for the status messages only in this case.
Then the normal message will be skipped by node-red

**Comment by ozett** [comment]
i found this:
https://docs.openmqttgateway.com/use/ble.html#receiving-signals-from-ble-beacon-devices-for-presence-detection
seems same functionality and a bit more configurable over mqtt.
will try to find the featureset for me ..
