### ISSUE TITLE
[FR:] Web-GUI information about Detail-Report

### ISSUE THREAD

**Issue by ozett** [redakker/blecker#22]
add some information for that drop-down.

maybe: "json output of rssi, mac, ..."
or link to help-page on github..

actual-state: 

![image](https://user-images.githubusercontent.com/5937811/156525922-d4bab642-6ea2-4dd0-bab5-a8e0350400a5.png)

**Comment by redakker** [comment]
The documentation describes the purpose of this dropdown.

**Comment by ozett** [comment]
ok
