### ISSUE TITLE
Compile the version into the binary

### ISSUE THREAD

**Issue by redakker** [redakker/blecker#23]
Currently, the web frontend displays v-orig for version if you upload the firmware directly. It displays the version if it was uploaded by OTA.
Compile the version for each binary then it will display the current version always

**Comment by redakker** [comment]
Implemented, documented
version changed to 1.07

**Comment by ozett** [comment]
i flashed 1.07 OTA and binary from usb.
all my old configs were gone. by default?
was back in the game in 1 minute. but i was wondering...

**Comment by redakker** [comment]
@ozett 
Probably because of the network connection.
Javascript loads the data after the page is displayed.
The config should not be touched after the OTA update
Thanks, every test is appreciated

**Comment by ozett** [comment]
will try next version update again.
and report. 
keep on good work on this! thanks
