### ISSUE TITLE
Observed devices status update on reconnect

### ISSUE THREAD

**Issue by Goodwillson** [redakker/blecker#36]
Shouldnt be sent message about observed devices status on each reconnect to reflect changes which happend during wifi/mqtt server connection downtime? Lets say the wifi/mqtt server downtime takes 10 minutes and some bluetooth devices appear/disappear during this time, we wont know current status untill periodic update which is every hour. At least make this behaviour optional.

**Comment by redakker** [comment]
I've checked the code it sends the status update every time when the client subscribes.
So if I solve ticket #35 then it should solve this issue as well.
