### ISSUE TITLE
Last will

### ISSUE THREAD

**Issue by Goodwillson** [redakker/blecker#37]
I found what is the problem of the non functional last will message. You have to move setLastWill(); call before you connect to mqtt broker, as the last will message must be defined before the actuall mqtt connection. Now its called after connection in topic subscription function. I cant test it, but I am sure thats it.

**Comment by redakker** [comment]
Thanks for the advice, I'll check it and fix it.

**Comment by redakker** [comment]
@Goodwillson 
I should connect to send the last will message. So I've put the last will send before the first interaction after the connect.
Please try it, I've put the binary to the dev_binary folder

**Comment by Goodwillson** [comment]
You really have to move it before you call connect, because the last will data is sent directly in that connection function in the library, look into row 898 in https://github.com/arduino-libraries/ArduinoMqttClient/blob/761ee7957facaa6315b0a74236c5f79b7c8c69b1/src/MqttClient.cpp

there is stated   flags |= _willFlags;

**Comment by Goodwillson** [comment]
Example https://github.com/arduino-libraries/ArduinoMqttClient/blob/ab5a0ce6eb3c2d00625597f7a18e193ea1356048/examples/WiFiAdvancedCallback/WiFiAdvancedCallback.ino

**Comment by Goodwillson** [comment]
Tested the last binary, does not set last will, make please above change and I will test it again.

**Comment by Goodwillson** [comment]
I applied my above suggestions together with #35 and it works as expected.
