### ISSUE TITLE
no webserver at 192.168.4.1

### ISSUE THREAD

**Issue by julianec** [redakker/blecker#44]
I tried to flash blecker_v1.08-107.bin and blecker_v1.10-116.bin. Both provide a wlan but no captive portal and no webserver at 192.168.4.1 on ios.

**Comment by julianec** [comment]
I tried joining the wifi via laptop without network cable and still couldn't find a webserver. Are the binaries in dev_binary the right ones?

**Comment by redakker** [comment]
@julianec in the folder is a dev binary. Try to pick a bin file from the releases.

**Comment by julianec** [comment]
It's the same with blecker_v1.09-114.bin and mobile data turned off. No captive portal and ERR_CONNECTION FAILED on 192.168.4.1.
