### ISSUE TITLE
iPhone not supported

### ISSUE THREAD

**Issue by chrigu1981** [redakker/blecker#45]
I tried this software and was surprised how easy it is to setup but unfortunately this does not work with iPhones.
One workaround could be to pair the esp32 with the iPhone. Maybe you guys would try this out :)

https://www.esp32.com/viewtopic.php?t=18856

**Comment by redakker** [comment]
Thanks for trying it out!
This project is for detecting BLE devices. As I know IPhone (phones overall) don't use BLE technique by default.
I recommend to use a dedicated BLE beacon (for ex. Nut) for this scanner.
