### ISSUE TITLE
ModuleNotFoundError: No module named 'htmlmin': when trying to build

### ISSUE THREAD

**Issue by victoroos** [redakker/blecker#6]
Hi, So, I just got my ESP board,
But when trying to upload (build) via VSC I get this error:
ModuleNotFoundError: No module named 'htmlmin':

What am I missing here?
Cheers
Victor

**Comment by redakker** [comment]
> Hi, So, I just got my ESP board, But when trying to upload (build) via VSC I get this error: ModuleNotFoundError: No module named 'htmlmin':
> 
> What am I missing here? Cheers Victor

Hi Victor,

I've added the build steps to the documentation. Try to follow that and it will work.
You need to install some python libraries and the Git
