### ISSUE TITLE
Presence string is sometimes broken

### ISSUE THREAD

**Issue by redakker** [redakker/blecker#63]
It happened when the device sent a message like:
- 1>
- {"st

Investigate why, and fix

**Comment by Goodwillson** [comment]
I just got similar string in log
![image](https://github.com/redakker/blecker/assets/46995056/2117ce9d-ff3c-4e89-8a58-61ce4e5f837e)

**Comment by redakker** [comment]
> I just got similar string in log
> ![image](https://github.com/redakker/blecker/assets/46995056/2117ce9d-ff3c-4e89-8a58-61ce4e5f837e)
> 

Thanks for the confirmation.
I'll check this bug as soon as possible.

**Comment by redakker** [comment]
It looks like the related commit solved this issue.
I've updated the release binary.

**Comment by Seinuh** [comment]
@redakker i'm running version 1.11.190 .. wich version got this fix ?
